print("My Name is Muhammad Hussnain")
print("My Father name is Nazir Ahmad")
print("I am a student Of 5th semester BSIT in universiy of Education, Township")
print("I am 20 year Old and I am from Kasur")
print("Thank You")